(define (print-abc a b c)
  (display a) (display " ")
  (display b) (display " ")
  (display c) (newline))
 
(define (foo a b c)
  (print-abc a b c)
  (let ((a 4)
        (c 5)
        (b c))
    (print-abc a b c)
    (let ((b 6)
          (c a))
      (print-abc a b c))
    (let ((a b)
          (c a))
      (print-abc a b c)))
  (print-abc a b c))
